version: '3.8'

services:
  discord-bot:
    build:
      context: https://github.com/yourusername/your-bot-repo.git
    env_file:
      - .env
    volumes:
      - quotes_db:/app/quotes.db
    restart: unless-stopped

volumes:
  quotes_db:
